// (c) 2010-2017 IndiegameGarden.com. Distributed under the FreeBSD license in LICENSE.txt

using Microsoft.Xna.Framework;
using Artemis;
using TTengine.Comps;

namespace TTengineTest
{
    /// <summary>
    /// Test the FxSprite, which is a sprite rect filled with contents generated by a shader fx.
    /// </summary>
    class TestFxSprite2: Test
    {

        public TestFxSprite2()
        {
            this.BackgroundColor = Color.Black;
        }

        public override void BuildAll()
        {
            var fx = CreateCloudFxSprite(New(),"clouds-texture");         
        }

        public Entity CreateCloudFxSprite(Entity e, string textureName)
        {
            using (BuildTo(CreateFx(New(), "clouds")))
            {
                CreateSprite(e, textureName);
                ProcessFitSize(e, BuildScreen);
                var p = GetFxParameters(e);
                AddScript(e, (ctx) =>
                    {
                        var t = (float)ctx.SimTime;
                        p["Position"].SetValue(new Vector2(30*t, 40*t));
                    }
                );
            }
            return e;
        }



    }
}
